### PR TITLE
Choose which week to show after shrink()

### PR DESCRIPTION
**Pull request by polyvjk**
- I added the possibility to choose which week of the month to show after shrink(). Simple use case:  the calendar is expanded, the user marks a date and then shrinks it, the week with the selected date should be visible (it was always the current week or the first of the month).

- There was a bug with the expansion after scrolling weeks. When you scroll the week view couple of times and go to another month, then expand the calendar it didn't show the new month.

### CODE REVIEW

**Comment by SpongeBobSun** [comment]
Awesome. Thanks.

**Comment by curiousily** [comment]
Hi @SpongeBobSun,

I work with @polyvjk and we were wondering if it possible to release a new version including this fix?

Thanks!

**Comment by SpongeBobSun** [comment]
@curiousily  @polyvjk  

Done.

Try  `compile 'sun.bob:mcalendarview:1.1.0'` for new changes and fixes.

Any questions please let me know.

Thanks.

**Comment by polyvjk** [comment]
Great, thanks :) We will send a link to our app when we release an alpha version :)

**Comment by SpongeBobSun** [comment]
Cool

**Pull request merged**
